/**
 * About Wevenu — trust page copy.
 * Hero is the venue owner. Never corporate. Never "amazing AI."
 */

export const ABOUT_PAGE = {
  why: {
    eyebrow: "About Wevenu",
    headline: "We didn't set out to build software.\nWe set out to protect hospitality.",
    paragraphs: [
      "Independent venues create some of life's most meaningful celebrations.",
      "But behind every beautiful event is an extraordinary amount of invisible work.",
      "Too many systems.",
      "Too many repeated conversations.",
      "Too much information living in too many places.",
      "We believed the people creating unforgettable experiences deserved technology that felt just as thoughtful.",
      "That belief became Wevenu.",
    ],
    cta: "Request a Walkthrough",
  },
  whatWeSaw: {
    headline: "The problem was never effort.\nIt was fragmentation.",
    paragraphs: [
      "Every venue already has incredible people.",
      "Owners.",
      "Managers.",
      "Coordinators.",
      "Preferred vendors.",
      "Families.",
      "Guests.",
      "The problem wasn't that anyone cared less.",
      "The problem was that every conversation started over somewhere else.",
      "One inquiry lived in email.",
      "Contracts lived somewhere different.",
      "Planning happened in spreadsheets.",
      "Payments somewhere else.",
      "Timelines somewhere else again.",
      "Everyone worked hard.",
      "No one worked together.",
    ],
  },
  belief: {
    headline: "Hospitality should never feel like administration.",
    paragraphs: [
      "Technology should disappear.",
      "The venue should remain.",
      "The software shouldn't become the experience.",
      "It should quietly support the people creating it.",
      "Every decision inside Wevenu starts with one question:",
      '"Does this make hospitality feel more human?"',
      "If the answer is no...",
      "we don't build it.",
    ],
  },
  howWeBuilt: {
    eyebrow: "One living record",
    headline: "Connected.\nNot integrated.",
    paragraphs: [
      "Most software connects separate systems.",
      "Wevenu was designed differently.",
      "Every inquiry...",
      "Every proposal...",
      "Every conversation...",
      "Every payment...",
      "Every task...",
      "Every vendor...",
      "Every guest...",
      "belongs to one living record.",
      "Nothing has to be synchronized because nothing was separated in the first place.",
      "That changes everything.",
    ],
  },
  promise: {
    headline: "Calm isn't a design style.\nIt's a product decision.",
    paragraphs: [
      "You'll never find unnecessary complexity.",
      "Or features built for a marketing brochure.",
      "Or technology added because it was fashionable.",
      "Every screen.",
      "Every workflow.",
      "Every recommendation.",
      "Exists for one purpose.",
      "Helping venues spend less time managing software...",
      "and more time creating extraordinary experiences.",
    ],
  },
  luv: {
    headline: "Technology should feel like another member of your team.",
    paragraphs: [
      "Luv wasn't created to replace people.",
      "Luv exists to notice the things busy humans miss.",
      "A couple waiting for a reply.",
      "A vendor missing information.",
      "A timeline conflict.",
      "A task that's quietly slipping.",
      "Gentle guidance.",
      "Thoughtful recommendations.",
      "Always available.",
      "Never intrusive.",
      "Hospitality first.",
      "Artificial intelligence second.",
    ],
  },
  who: {
    headline: "Wevenu isn't for everyone.",
    paragraphs: [
      "It's for independent venues that believe hospitality is personal.",
      "For owners who know every event is different.",
      "For teams who remember guests by name.",
      "For places where reputation matters more than scale.",
      "If that sounds familiar...",
      "you're exactly why we built this.",
    ],
  },
  interstitial: {
    line: "The best hospitality is remembered.\nThe best software isn't.",
  },
  invitation: {
    headline: "We'd love to show you around.",
    paragraphs: [
      "Not a sales presentation.",
      "Not a pressure call.",
      "Just a conversation about your venue.",
      "We'll show you how Wevenu works.",
      "We'll answer every question.",
      "And if it isn't the right fit...",
      "we'll tell you that too.",
    ],
    cta: "Request a Walkthrough",
  },
} as const;
