/**
 * Features catalog — scannable inventory of everything included.
 * Not a sales brochure; answers “Does Wevenu have everything I need?”
 */

export const FEATURES_PAGE = {
  hero: {
    headline: "Everything your venue needs.",
    lines: [
      "Every capability in Wevenu, thoughtfully organized around how independent venues actually work.",
      "No jargon.",
      "No feature hunting.",
      "Just one place to see everything included.",
    ],
  },
  sections: [
    {
      id: "sales-bookings",
      title: "Sales & Bookings",
      intro: "Helping every inquiry become a beautifully managed booking.",
      features: [
        "Lead Capture",
        "Inquiry Consolidation",
        "Customizable Sales Pipelines",
        "Tour Scheduling",
        "Proposal Builder",
        "Digital Contracts",
        "Flexible Payment Plans",
        "Automated Follow-up",
        "Email Templates",
        "Text Messaging",
        "Workflow Automation",
        "Calendar Sync",
        "Activity Timeline",
        "Lead Assignment",
      ],
    },
    {
      id: "planning",
      title: "Planning",
      intro: "Everything your team and your clients need between booking and celebration.",
      features: [
        "Planning Playbooks",
        "Collaborative Planning",
        "Planning Checklists",
        "Questionnaires",
        "Timeline Builder",
        "Document Sharing",
        "Notes",
        "File Storage",
        "Client Tasks",
        "Planning Calendar",
        "Activity History",
        "Internal Collaboration",
      ],
    },
    {
      id: "venue-operations",
      title: "Venue Operations",
      intro: "The operational heartbeat of every event.",
      features: [
        "Floor Plans",
        "Seating Charts",
        "Inventory Management",
        "Rental Items",
        "Packages",
        "Venue Spaces",
        "Event Timeline",
        "Staff Coordination",
        "Event Notes",
        "Day-of Checklists",
        "Room Layouts",
        "Setup Tracking",
      ],
    },
    {
      id: "vendor-collaboration",
      title: "Vendor Collaboration",
      intro: "Keeping every vendor informed without endless emails.",
      features: [
        "Vendor Directory",
        "Vendor Invitations",
        "Vendor Portal",
        "Timeline Visibility",
        "Shared Documents",
        "Vendor Messaging",
        "Vendor Notes",
        "Vendor Assignments",
        "Preferred Vendors",
      ],
    },
    {
      id: "client-experience",
      title: "Client Experience",
      intro: "An experience that reflects your venue—not another generic portal.",
      features: [
        "Branded Client Portal",
        "Shared Planning Workspace",
        "Messages",
        "Documents",
        "Timeline Access",
        "Planning Progress",
        "Task Completion",
        "Secure File Sharing",
      ],
    },
    {
      id: "guest-experience",
      title: "Guest Experience",
      intro: "Helping guests arrive informed, confident, and excited.",
      features: [
        "Guest Portal",
        "RSVP Management",
        "Travel Information",
        "Maps & Directions",
        "FAQs",
        "Schedule",
        "Photo Galleries",
        "Announcements",
        "Event Details",
      ],
    },
    {
      id: "financials",
      title: "Financials",
      intro: "Keeping every dollar connected to the celebration.",
      features: [
        "Invoices",
        "Deposits",
        "Payment Plans",
        "Online Payments",
        "Refund Tracking",
        "Outstanding Balances",
        "Financial Reporting",
        "Revenue Dashboard",
      ],
    },
    {
      id: "administration",
      title: "Administration",
      intro: "Everything needed to manage your venue behind the scenes.",
      features: [
        "White Label Branding",
        "Multi-user Permissions",
        "Venue Settings",
        "Import Existing Data",
        "Export Data",
        "Notifications",
        "Dashboard",
        "Reporting",
        "Audit History",
        "Mobile Friendly",
      ],
    },
    {
      id: "luv-intelligence",
      title: "Luv Intelligence",
      intro:
        "Thoughtful recommendations that help your venue scale hospitality without losing heart.",
      features: [
        "Morning Briefings",
        "Smart Recommendations",
        "Venue Health",
        "Opportunity Detection",
        "AI-assisted Drafts",
        "Intelligent Reminders",
        "Contextual Suggestions",
      ],
    },
  ],
  close: {
    headline: "Everything connected.",
    lines: [
      "No switching between disconnected systems.",
      "No duplicate entry.",
      "No wondering which version is correct.",
      "Just one calm workspace built around how independent venues actually operate.",
    ],
  },
} as const;
