/**
 * Features catalog — scannable inventory of everything included.
 * Not a sales brochure; answers “Does Hello to Cheers have everything I need?”
 */

export const FEATURES_PAGE = {
  hero: {
    eyebrow: "Features",
    chapterTitle: "Everything Included",
    headline: "Everything your venue needs.",
    lines: [
      "Every capability in Hello to Cheers, thoughtfully organized around how independent venues actually work.",
      "No jargon.",
      "No feature hunting.",
      "Just one place to see everything included.",
    ],
  },
  sections: [
    {
      id: "sales-bookings",
      title: "Sales & Bookings",
      intro: "Helping every inquiry become a beautifully managed booking.",
      features: [
        "Lead Capture",
        "Inquiry Consolidation",
        "Customizable Sales Pipelines",
        "Tour Scheduling",
        "Interactive Proposals",
        "Digital Contracts",
        "Flexible Payment Plans",
        "Automated Follow-up",
        "Email Templates",
        "Text Messaging",
        "Workflow Automation",
        "Calendar Sync",
        "Activity Timeline",
        "Lead Assignment",
      ],
    },
    {
      id: "planning",
      title: "Planning",
      intro: "Everything your team and your clients need between booking and celebration.",
      features: [
        "Reusable Planning Templates",
        "Venue Planning Tasks",
        "Collaborative Planning",
        "Client Questionnaires",
        "Timeline Builder",
        "Planning Calendar",
        "Client Portal Tasks",
        "Document Sharing",
        "File Library",
        "Notes",
        "Activity History",
        "Team Collaboration",
      ],
    },
    {
      id: "client-experience",
      title: "Client Experience",
      intro: "An experience that reflects your venue—not another generic portal.",
      features: [
        "Branded Client Portal",
        "Shared Planning Workspace",
        "Messages",
        "Documents",
        "Timeline Access",
        "Planning Progress",
        "Task Completion",
        "Secure File Sharing",
      ],
    },
    {
      id: "venue-operations",
      title: "Venue Operations",
      intro: "The operational heartbeat of every event.",
      features: [
        "Venue Spaces",
        "Floor Plans & Layouts",
        "Seating Charts",
        "Packages",
        "Inventory & Rentals",
        "Event Timeline",
        "Team Coordination",
        "Setup Tracking",
        "Day-of Checklists",
        "Event Notes",
      ],
    },
    {
      id: "vendor-collaboration",
      title: "Vendor Collaboration",
      intro: "Keeping every vendor informed without endless emails.",
      features: [
        "Vendor Directory",
        "Preferred Vendors",
        "Vendor Invitations",
        "Shared Planning Workspace",
        "Shared Timeline",
        "Shared Documents",
        "Messages & Conversations",
        "Vendor Responsibilities",
        "Vendor Notes",
      ],
    },
    {
      id: "guest-experience",
      title: "Guest Experience",
      intro: "Helping guests arrive informed, confident, and excited.",
      features: [
        "Guest Portal",
        "RSVP Management",
        "Travel Information",
        "Maps & Directions",
        "FAQs",
        "Schedule",
        "Photo Galleries",
        "Announcements",
        "Event Details",
      ],
    },
    {
      id: "financials",
      title: "Financials",
      intro: "Every dollar connected to every celebration.",
      features: [
        "Payment Plans",
        "Invoices",
        "Online Payments",
        "Deposits",
        "Outstanding Balances",
        "Refund Tracking",
        "Revenue Dashboard",
        "Financial Reporting",
        "QuickBooks Integration",
      ],
    },
    {
      id: "venue-management",
      title: "Venue Management",
      intro: "Everything that keeps your venue running beautifully behind the scenes.",
      features: [
        "Venue Profile",
        "Venue Guide & FAQs",
        "Venue Branding",
        "Team Permissions",
        "Custom Notifications",
        "Dashboard",
        "Reporting",
        "Data Import & Export",
        "Audit History",
        "Mobile Friendly",
      ],
    },
    {
      id: "meet-luv",
      title: "Meet Luv.",
      intro:
        "Thoughtful recommendations that help your venue scale hospitality without losing heart.",
      features: [
        "Daily Briefings",
        "Helpful Drafts",
        "Smart Reminders",
        "Venue Health",
        "Conversation Summaries",
        "Opportunity Insights",
        "Thoughtful Suggestions",
      ],
    },
  ],
  close: {
    headline: "Everything connected.",
    lines: [
      "No switching between disconnected systems.",
      "No duplicate entry.",
      "No wondering which version is correct.",
      "Just one calm workspace built around how venues actually operate.",
    ],
  },
} as const;
