/**
 * Guided Setup §1.1 (2026-07-22) — setup gaps become `recommendation`-kind
 * LuvObservations, generated by reading the Activation Engine's own
 * checklist, never recomputing it. Same "read, never recompute" rule the
 * rest of Luv's observation feed already follows for Event Readiness and
 * Communication Health. This is the concrete mechanism behind "I noticed
 * your website isn't collecting inquiries yet" — a gap-to-observation
 * translation of data that already exists, not a new source of truth.
 *
 * Capped at the top 3 by points (mirroring how compute_venue_
 * activation_score() itself already caps `.gaps`) so a brand-new venue
 * with a dozen incomplete items doesn't flood the feed — the Getting
 * Started card is still the complete list; this is Luv surfacing the
 * highest-leverage ones proactively.
 */
import { GAP_COPY } from "@/lib/dashboard/gap-copy";
import type { ActivationChecklistItem } from "@/lib/activation/types";
import type { LuvObservation } from "@/lib/luv/types";

export function computeSetupGapObservations(checklist: ActivationChecklistItem[]): LuvObservation[] {
  const topGaps = [...checklist]
    .filter((item) => !item.completed)
    .sort((a, b) => b.points - a.points)
    .slice(0, 3);

  return topGaps.map((item) => {
    const copy = GAP_COPY[item.key];
    const ctaLabel = copy?.ctaLabel ?? "Take me there";
    return {
      id: `setup-gap-${item.key}`,
      kind: "recommendation",
      priority: "medium",
      message: copy?.title ?? item.label,
      detail: copy?.description ?? item.label,
      link: item.href,
      actionLabel: `${ctaLabel} →`,
      recommendation: { label: ctaLabel, link: item.href, type: "navigate" },
    };
  });
}
