"use client";

/**
 * WebsiteEditor — inline section-by-section editor for the couple's wedding website.
 *
 * Design principle: "The website should feel like 'Our wedding website.'
 * Not 'A page generated by venue software.'"
 *
 * UX: accordion sections. Each section shows a preview when collapsed.
 * Click Edit → form fields appear → Save updates via /api/portal/website.
 * No page reload needed — optimistic updates.
 */

import * as React from "react";
import { Check, ChevronDown, ChevronUp, Copy, ExternalLink, Image, Loader2, Mail, Palette, Plus, Smartphone, Trash2, X } from "lucide-react";
import { toast } from "sonner";

import type { CoupleWebsite, WebsiteContent, WebsiteTheme } from "@/lib/wedding-website/types";

type Section = {
  key: string;
  title: string;
  emoji: string;
  description: string;
  preview?: (content: WebsiteContent) => string | null;
};

const SECTIONS: Section[] = [
  { key: "home",     emoji: "🌿", title: "Home & Welcome",   description: "Your headline, subtitle, and welcome message.", preview: c => c.home?.title || c.home?.welcomeMessage || null },
  { key: "story",    emoji: "💗", title: "Your Story",        description: "How you met — the most personal part of your website.", preview: c => (c as any).story?.text?.slice(0, 60) || null },
  { key: "event",    emoji: "📍", title: "Event Details",     description: "Ceremony and reception times, locations, and addresses.", preview: c => c.event?.ceremony?.location || c.event?.reception?.location || null },
  { key: "schedule", emoji: "📋", title: "Day-of Schedule",   description: "A timeline for your guests.", preview: c => c.schedule?.length ? `${c.schedule.length} schedule items` : null },
  { key: "travel",   emoji: "🏨", title: "Travel & Hotels",   description: "Hotel blocks, transportation notes, and travel info.", preview: c => c.travel?.hotels?.[0]?.name || c.travel?.message?.slice(0, 50) || null },
  { key: "registry", emoji: "🎁", title: "Registry",          description: "Links to your registries.", preview: c => c.registry?.length ? `${c.registry.length} registr${c.registry.length === 1 ? "y" : "ies"}` : null },
  { key: "faq",      emoji: "❓", title: "FAQ",               description: "Common guest questions and answers.", preview: c => c.faq?.length ? `${c.faq.length} question${c.faq.length === 1 ? "" : "s"}` : null },
];

const THEMES: { value: WebsiteTheme; label: string; preview: string }[] = [
  { value: "classic",  label: "Classic",  preview: "#5D6F5D" },
  { value: "modern",   label: "Modern",   preview: "#1A1A1A" },
  { value: "garden",   label: "Garden",   preview: "#7A9A5A" },
  { value: "minimal",  label: "Minimal",  preview: "#F5F4F2" },
];

const ACCENT_COLORS = [
  { value: "#5D6F5D", label: "Heritage Sage" },
  { value: "#D8A7AA", label: "Dusty Rose" },
  { value: "#2C3E6B", label: "Navy Blue" },
  { value: "#C9A96E", label: "Champagne" },
  { value: "#7A9A5A", label: "Garden" },
  { value: "#8B6E5A", label: "Warm Terracotta" },
];

// ── Photo upload helper ───────────────────────────────────────────────────────

function PhotoUpload({ token, type, label, currentUrl, onUploaded }: {
  token: string; type: string; label: string;
  currentUrl?: string; onUploaded: (url: string) => void;
}) {
  const [uploading, setUploading] = React.useState(false);
  const inputRef = React.useRef<HTMLInputElement>(null);

  async function handleFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    try {
      const form = new FormData();
      form.append("token", token);
      form.append("file", file);
      form.append("type", type);
      const res = await fetch("/api/portal/upload", { method: "POST", body: form });
      const data = await res.json() as { ok: boolean; url?: string; error?: string };
      if (data.ok && data.url) { onUploaded(data.url); toast.success(`${label} uploaded!`); }
      else toast.error(data.error ?? "Upload failed.");
    } catch { toast.error("Upload failed. Please try again."); }
    finally { setUploading(false); if (inputRef.current) inputRef.current.value = ""; }
  }

  return (
    <div className="space-y-1.5">
      <p className="text-[11px] font-medium text-muted-foreground">{label}</p>
      {currentUrl && (
        <div className="relative rounded-xl overflow-hidden h-24 bg-muted">
          <img src={currentUrl} alt={label} className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-black/20 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
            <span className="text-white text-xs font-medium">Change photo</span>
          </div>
        </div>
      )}
      <label className="flex items-center gap-2 cursor-pointer px-3 py-2.5 rounded-xl border border-dashed border-border hover:bg-muted/40 transition-colors">
        {uploading ? <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" /> : <Image className="h-4 w-4 text-muted-foreground" />}
        <span className="text-sm text-muted-foreground">{uploading ? "Uploading…" : currentUrl ? "Change photo" : `Upload ${label.toLowerCase()}`}</span>
        <input ref={inputRef} type="file" accept="image/*" className="sr-only" onChange={handleFile} disabled={uploading} />
      </label>
      <p className="text-[10px] text-muted-foreground">JPG, PNG, WebP up to 10MB</p>
    </div>
  );
}

// ── Section editors ───────────────────────────────────────────────────────────

function HomeEditor({ content, onSave, onCancel, token }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void; token: string }) {
  const [title, setTitle] = React.useState(content.home?.title ?? "");
  const [subtitle, setSubtitle] = React.useState(content.home?.subtitle ?? "");
  const [welcome, setWelcome] = React.useState(content.home?.welcomeMessage ?? "");
  const [coverUrl, setCoverUrl] = React.useState(content.home?.coverImageUrl ?? "");
  return (
    <div className="space-y-3">
      <PhotoUpload token={token} type="cover" label="Cover photo" currentUrl={coverUrl || undefined} onUploaded={url => setCoverUrl(url)} />
      <Field label="Page headline" value={title} onChange={setTitle} placeholder="Emily & James" />
      <Field label="Subtitle" value={subtitle} onChange={setSubtitle} placeholder="June 12, 2027 · Nashville, TN" />
      <TextareaField label="Welcome message" value={welcome} onChange={setWelcome} placeholder="We're so excited to celebrate with you! Join us for a day full of love, laughter, and joy." rows={3} />
      <Actions onSave={() => onSave({ title, subtitle, welcomeMessage: welcome, coverImageUrl: coverUrl || undefined })} onCancel={onCancel} />
    </div>
  );
}

function StoryEditor({ content, onSave, onCancel }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void }) {
  const story = (content as any).story ?? {};
  const [title, setTitle] = React.useState(story.title ?? "How We Met");
  const [text, setText] = React.useState(story.text ?? "");
  return (
    <div className="space-y-3">
      <Field label="Section title" value={title} onChange={setTitle} placeholder="How We Met" />
      <TextareaField label="Your story" value={text} onChange={setText} placeholder="We met at a coffee shop in Nashville on a rainy Tuesday morning. James spilled coffee on Emily's favorite book, and the rest is history..." rows={5} />
      <Actions onSave={() => onSave({ title, text })} onCancel={onCancel} />
    </div>
  );
}

function EventEditor({ content, onSave, onCancel }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void }) {
  const [cTime, setCTime] = React.useState(content.event?.ceremony?.time ?? "");
  const [cLocation, setCLocation] = React.useState(content.event?.ceremony?.location ?? "");
  const [cAddress, setCAddress] = React.useState(content.event?.ceremony?.address ?? "");
  const [rTime, setRTime] = React.useState(content.event?.reception?.time ?? "");
  const [rLocation, setRLocation] = React.useState(content.event?.reception?.location ?? "");
  const [rAddress, setRAddress] = React.useState(content.event?.reception?.address ?? "");
  return (
    <div className="space-y-4">
      <div className="space-y-2">
        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Ceremony</p>
        <Field label="Time" value={cTime} onChange={setCTime} placeholder="4:00 PM" />
        <Field label="Location" value={cLocation} onChange={setCLocation} placeholder="The Wildflower Estate" />
        <Field label="Address" value={cAddress} onChange={setCAddress} placeholder="123 Meadow Lane, Nashville, TN" />
      </div>
      <div className="space-y-2">
        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Reception</p>
        <Field label="Time" value={rTime} onChange={setRTime} placeholder="6:00 PM" />
        <Field label="Location" value={rLocation} onChange={setRLocation} placeholder="The Wildflower Estate Garden" />
        <Field label="Address" value={rAddress} onChange={setRAddress} placeholder="123 Meadow Lane, Nashville, TN" />
      </div>
      <Actions onSave={() => onSave({ ceremony: { time: cTime, location: cLocation, address: cAddress }, reception: { time: rTime, location: rLocation, address: rAddress } })} onCancel={onCancel} />
    </div>
  );
}

function ScheduleEditor({ content, onSave, onCancel, token, scheduleSync, onToggleSync }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void; token?: string; scheduleSync?: boolean; onToggleSync?: (v: boolean) => void }) {
  const [items, setItems] = React.useState<{ time: string; title: string; description: string }[]>(
    content.schedule?.map(i => ({ ...i, description: i.description ?? "" })) ?? []
  );
  const [guestTimeline, setGuestTimeline] = React.useState<{ time: string; title: string }[]>([]);
  const [loadingTimeline, setLoadingTimeline] = React.useState(false);

  React.useEffect(() => {
    if (!token || scheduleSync === false) return;
    setLoadingTimeline(true);
    fetch(`/api/portal/website/guest-timeline?token=${token}`)
      .then(r => r.json())
      .then((d: { entries?: { time: string; title: string }[] }) => setGuestTimeline(d.entries ?? []))
      .catch(() => {})
      .finally(() => setLoadingTimeline(false));
  }, [token, scheduleSync]);

  function add() { setItems(p => [...p, { time: "", title: "", description: "" }]); }
  function remove(i: number) { setItems(p => p.filter((_, j) => j !== i)); }
  function set(i: number, k: string, v: string) { setItems(p => p.map((item, j) => j === i ? { ...item, [k]: v } : item)); }

  const isSync = scheduleSync !== false;

  return (
    <div className="space-y-4">
      {/* Sync toggle */}
      {onToggleSync && (
        <div className="rounded-xl border border-border bg-muted/20 p-3 space-y-2">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold text-heading">
                {isSync ? "☑ Syncing from Event Timeline" : "○ Using custom content"}
              </p>
              <p className="text-[10px] text-muted-foreground mt-0.5">
                {isSync
                  ? "Timeline entries tagged 🌿 Guests appear here automatically."
                  : "You've overridden with custom schedule items below."}
              </p>
            </div>
            <button type="button" onClick={() => onToggleSync(!isSync)}
              className="text-xs text-muted-foreground hover:text-foreground underline-offset-2 hover:underline shrink-0">
              {isSync ? "Use custom" : "Sync from timeline"}
            </button>
          </div>

          {isSync && (
            loadingTimeline ? (
              <p className="text-[10px] text-muted-foreground">Loading timeline entries…</p>
            ) : guestTimeline.length > 0 ? (
              <div className="space-y-1">
                {guestTimeline.map((e, i) => (
                  <div key={i} className="flex items-center gap-2 text-xs">
                    <span className="text-muted-foreground w-16 shrink-0">{e.time?.slice(0, 5) ?? ""}</span>
                    <span className="text-heading">{e.title}</span>
                  </div>
                ))}
                <a href="#" onClick={e => { e.preventDefault(); window.open(window.location.href.replace(/\/p\/.*/, "/timeline"), "_blank"); }}
                  className="text-[10px] text-muted-foreground hover:text-foreground underline-offset-2 hover:underline block mt-1">
                  Edit timeline to add more guest-facing items →
                </a>
              </div>
            ) : (
              <p className="text-[10px] text-muted-foreground">
                No guest-facing timeline entries yet. Go to the event's Timeline tab and tag entries 🌿 Guests.
              </p>
            )
          )}
        </div>
      )}

      {/* Custom items — only when not syncing */}
      {!isSync && (
        <>
          {items.map((item, i) => (
            <div key={i} className="flex gap-2 items-start rounded-xl border border-border bg-muted/20 p-3">
              <div className="flex-1 grid grid-cols-2 gap-2">
                <input value={item.time} onChange={e => set(i, "time", e.target.value)} placeholder="4:00 PM" className="col-span-1 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
                <input value={item.title} onChange={e => set(i, "title", e.target.value)} placeholder="Ceremony begins" className="col-span-1 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
                <input value={item.description} onChange={e => set(i, "description", e.target.value)} placeholder="Description (optional)" className="col-span-2 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
              </div>
              <button type="button" onClick={() => remove(i)} className="shrink-0 p-1.5 text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
            </div>
          ))}
          <button type="button" onClick={add} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">
            <Plus className="h-3.5 w-3.5" /> Add schedule item
          </button>
          <Actions onSave={() => onSave(items.filter(i => i.title.trim()))} onCancel={onCancel} />
        </>
      )}

      {isSync && (
        <div className="flex justify-end">
          <button type="button" onClick={onCancel} className="text-sm text-muted-foreground px-3 py-1.5 rounded-xl hover:bg-muted">Close</button>
        </div>
      )}
    </div>
  );
}

function TravelEditor({ content, onSave, onCancel }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void }) {
  const [message, setMessage] = React.useState(content.travel?.message ?? "");
  const [hotels, setHotels] = React.useState<{ name: string; url: string; code: string; notes: string }[]>(
    content.travel?.hotels?.map(h => ({ name: h.name, url: h.url ?? "", code: h.code ?? "", notes: h.notes ?? "" })) ?? []
  );
  const [transport, setTransport] = React.useState(content.travel?.transportation?.notes ?? "");
  function addHotel() { setHotels(p => [...p, { name: "", url: "", code: "", notes: "" }]); }
  function removeHotel(i: number) { setHotels(p => p.filter((_, j) => j !== i)); }
  function setH(i: number, k: string, v: string) { setHotels(p => p.map((h, j) => j === i ? { ...h, [k]: v } : h)); }
  return (
    <div className="space-y-4">
      <TextareaField label="Travel message" value={message} onChange={setMessage} placeholder="We've reserved a room block at the Marriott. Use code CARTER2027 for 20% off." rows={2} />
      <div className="space-y-2">
        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Hotel blocks</p>
        {hotels.map((h, i) => (
          <div key={i} className="rounded-xl border border-border bg-muted/20 p-3 space-y-2">
            <input value={h.name} onChange={e => setH(i, "name", e.target.value)} placeholder="Hotel name *" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
            <div className="grid grid-cols-2 gap-2">
              <input value={h.code} onChange={e => setH(i, "code", e.target.value)} placeholder="Booking code" className="rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
              <input value={h.url} onChange={e => setH(i, "url", e.target.value)} placeholder="Booking URL" className="rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
            </div>
            <div className="flex gap-2">
              <input value={h.notes} onChange={e => setH(i, "notes", e.target.value)} placeholder="Notes" className="flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
              <button type="button" onClick={() => removeHotel(i)} className="p-2 text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
            </div>
          </div>
        ))}
        <button type="button" onClick={addHotel} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">
          <Plus className="h-3.5 w-3.5" /> Add hotel block
        </button>
      </div>
      <TextareaField label="Transportation notes" value={transport} onChange={setTransport} placeholder="Shuttle buses will run from the Marriott to the venue every 30 minutes starting at 3:30 PM." rows={2} />
      <Actions onSave={() => onSave({ message, hotels: hotels.filter(h => h.name.trim()), transportation: { notes: transport } })} onCancel={onCancel} />
    </div>
  );
}

function RegistryEditor({ content, onSave, onCancel }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void }) {
  const [items, setItems] = React.useState<{ name: string; url: string; notes: string }[]>(
    content.registry?.map(r => ({ name: r.name, url: r.url, notes: r.notes ?? "" })) ?? []
  );
  function add() { setItems(p => [...p, { name: "", url: "", notes: "" }]); }
  function remove(i: number) { setItems(p => p.filter((_, j) => j !== i)); }
  function set(i: number, k: string, v: string) { setItems(p => p.map((r, j) => j === i ? { ...r, [k]: v } : r)); }
  return (
    <div className="space-y-3">
      {items.map((item, i) => (
        <div key={i} className="flex gap-2 items-start rounded-xl border border-border bg-muted/20 p-3">
          <div className="flex-1 space-y-2">
            <input value={item.name} onChange={e => set(i, "name", e.target.value)} placeholder="Registry name (e.g., Crate & Barrel)" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
            <input value={item.url} onChange={e => set(i, "url", e.target.value)} placeholder="URL" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
          </div>
          <button type="button" onClick={() => remove(i)} className="shrink-0 p-1.5 text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
        </div>
      ))}
      <button type="button" onClick={add} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">
        <Plus className="h-3.5 w-3.5" /> Add registry
      </button>
      <Actions onSave={() => onSave(items.filter(i => i.name.trim() && i.url.trim()))} onCancel={onCancel} />
    </div>
  );
}

function FaqEditor({ content, onSave, onCancel }: { content: WebsiteContent; onSave: (v: object) => void; onCancel: () => void }) {
  const [items, setItems] = React.useState<{ question: string; answer: string }[]>(
    content.faq ?? []
  );
  function add() { setItems(p => [...p, { question: "", answer: "" }]); }
  function remove(i: number) { setItems(p => p.filter((_, j) => j !== i)); }
  function set(i: number, k: string, v: string) { setItems(p => p.map((item, j) => j === i ? { ...item, [k]: v } : item)); }
  return (
    <div className="space-y-3">
      {items.map((item, i) => (
        <div key={i} className="rounded-xl border border-border bg-muted/20 p-3 space-y-2">
          <div className="flex items-start gap-2">
            <div className="flex-1 space-y-2">
              <input value={item.question} onChange={e => set(i, "question", e.target.value)} placeholder="Question" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none" />
              <textarea value={item.answer} onChange={e => set(i, "answer", e.target.value)} placeholder="Answer" rows={2} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none resize-none" />
            </div>
            <button type="button" onClick={() => remove(i)} className="shrink-0 p-1.5 text-muted-foreground hover:text-destructive mt-0.5"><Trash2 className="h-3.5 w-3.5" /></button>
          </div>
        </div>
      ))}
      <button type="button" onClick={add} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">
        <Plus className="h-3.5 w-3.5" /> Add FAQ
      </button>
      <Actions onSave={() => onSave(items.filter(i => i.question.trim()))} onCancel={onCancel} />
    </div>
  );
}

// ── Field helpers ─────────────────────────────────────────────────────────────

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) {
  return (
    <div className="space-y-1">
      <p className="text-[11px] font-medium text-muted-foreground">{label}</p>
      <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
        className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-ring" />
    </div>
  );
}

function TextareaField({ label, value, onChange, placeholder, rows = 3 }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; rows?: number }) {
  return (
    <div className="space-y-1">
      <p className="text-[11px] font-medium text-muted-foreground">{label}</p>
      <textarea value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} rows={rows}
        className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-ring resize-none" />
    </div>
  );
}

function Actions({ onSave, onCancel }: { onSave: () => void; onCancel: () => void }) {
  return (
    <div className="flex justify-end gap-2 pt-1">
      <button type="button" onClick={onCancel} className="text-sm text-muted-foreground px-3 py-1.5 rounded-xl hover:bg-muted">Cancel</button>
      <button type="button" onClick={onSave} className="text-sm font-medium px-4 py-1.5 rounded-xl bg-[#5D6F5D] text-white hover:opacity-90">Save</button>
    </div>
  );
}

// ── Section accordion item ────────────────────────────────────────────────────

function SectionAccordion({ section, content, onSaveSection, saving, token, scheduleSync, onToggleSync }: {
  section: Section;
  content: WebsiteContent;
  onSaveSection: (key: string, value: object) => Promise<void>;
  saving: string | null;
  token: string;
  scheduleSync?: boolean;
  onToggleSync?: (v: boolean) => void;
}) {
  const [open, setOpen] = React.useState(false);
  const previewText = section.preview?.(content);
  const hasContent = !!previewText;

  function EditorFor() {
    const props = {
      content,
      onSave: async (v: object) => { await onSaveSection(section.key, v); setOpen(false); },
      onCancel: () => setOpen(false),
    };
    switch (section.key) {
      case "home":     return <HomeEditor {...props} token={token} />;
      case "story":    return <StoryEditor {...props} />;
      case "event":    return <EventEditor {...props} />;
      case "schedule": return <ScheduleEditor {...props} token={token} scheduleSync={scheduleSync} onToggleSync={onToggleSync} />;
      case "travel":   return <TravelEditor {...props} />;
      case "registry": return <RegistryEditor {...props} />;
      case "faq":      return <FaqEditor {...props} />;
      default:         return null;
    }
  }

  return (
    <div className={`rounded-2xl border transition-colors ${open ? "border-ring bg-card" : "border-border bg-card"}`}>
      <button type="button" onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-3 px-4 py-3.5 text-left">
        <span className="text-lg shrink-0">{section.emoji}</span>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <p className="text-sm font-medium text-heading">{section.title}</p>
            {hasContent ? (
              <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded-full bg-green-50 text-green-700">✓ Added</span>
            ) : (
              <span className="text-[10px] text-muted-foreground">Tap to add</span>
            )}
            {saving === section.key && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />}
          </div>
          {hasContent && !open && (
            <p className="text-[11px] text-muted-foreground truncate mt-0.5">{previewText}</p>
          )}
        </div>
        {open ? <ChevronUp className="h-4 w-4 text-muted-foreground shrink-0" /> : <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" />}
      </button>
      {open && (
        <div className="px-4 pb-4 border-t border-border/50 pt-4">
          <p className="text-xs text-muted-foreground mb-3">{section.description}</p>
          <EditorFor />
        </div>
      )}
    </div>
  );
}

// ── Appearance section ────────────────────────────────────────────────────────

function AppearanceSection({ site, onUpdate }: { site: CoupleWebsite; onUpdate: (patch: Partial<CoupleWebsite>) => void }) {
  const [open, setOpen] = React.useState(false);
  return (
    <div className={`rounded-2xl border transition-colors ${open ? "border-ring bg-card" : "border-border bg-card"}`}>
      <button type="button" onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-3 px-4 py-3.5 text-left">
        <Palette className="h-5 w-5 text-muted-foreground shrink-0" />
        <div className="flex-1">
          <p className="text-sm font-medium text-heading">Appearance</p>
          <p className="text-[11px] text-muted-foreground">{THEMES.find(t => t.value === site.theme)?.label ?? "Classic"} theme</p>
        </div>
        {open ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
      </button>
      {open && (
        <div className="px-4 pb-4 border-t border-border/50 pt-4 space-y-4">
          <div className="space-y-2">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Theme</p>
            <div className="grid grid-cols-2 gap-2">
              {THEMES.map(t => (
                <button key={t.value} type="button" onClick={() => onUpdate({ theme: t.value })}
                  className={`rounded-xl border py-3 text-sm font-medium transition-colors ${site.theme === t.value ? "ring-2 ring-ring ring-offset-1" : ""}`}
                  style={{ borderColor: t.preview, background: `${t.preview}15` }}>
                  {t.label}
                </button>
              ))}
            </div>
          </div>
          <div className="space-y-2">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Accent color</p>
            <div className="flex gap-2 flex-wrap">
              {ACCENT_COLORS.map(c => (
                <button key={c.value} type="button" onClick={() => onUpdate({ accentColor: c.value })}
                  className={`h-8 w-8 rounded-full border-2 transition-all ${site.accentColor === c.value ? "ring-2 ring-offset-2 ring-ring scale-110" : "border-white/50"}`}
                  style={{ background: c.value }}
                  title={c.label} />
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main editor ───────────────────────────────────────────────────────────────

export function WebsiteEditor({
  token, initialSite, origin, initialGuests,
}: { token: string; initialSite: CoupleWebsite; origin: string; initialGuests?: { id: string; firstName: string; lastName: string | null; email: string | null; rsvpStatus: string; rsvpSentAt?: string | null }[] }) {
  const [site, setSite] = React.useState(initialSite);
  const [content, setContent] = React.useState<WebsiteContent>(initialSite.content ?? {});
  const [saving, setSaving] = React.useState<string | null>(null);
  const [publishing, setPublishing] = React.useState(false);
  const [previewMode, setPreviewMode] = React.useState<"desktop" | "mobile">("mobile");
  const [showPreview, setShowPreview] = React.useState(false);
  const [showQR, setShowQR] = React.useState(false);
  const [scheduleSync, setScheduleSync] = React.useState(
    (initialSite as CoupleWebsite & { scheduleSync?: boolean }).scheduleSync !== false
  );
  const [showInvite, setShowInvite] = React.useState(false);
  const [selectedGuests, setSelectedGuests] = React.useState<string[]>([]);
  const [sendingInvites, setSendingInvites] = React.useState(false);
  const [views, setViews] = React.useState<{ totalViews: number; weekViews: number } | null>(null);
  const guests = initialGuests ?? [];

  const websiteUrl = site.slug ? `${origin}/w/${site.slug}` : null;
  const completedSections = SECTIONS.filter(s => s.preview?.(content)).length;

  // Fetch analytics
  React.useEffect(() => {
    if (!site.isPublished) return;
    fetch(`/api/portal/website/analytics?token=${token}`)
      .then(r => r.json())
      .then((d: { totalViews?: number; weekViews?: number }) => {
        if (d.totalViews !== undefined) setViews({ totalViews: d.totalViews, weekViews: d.weekViews ?? 0 });
      })
      .catch(() => {});
  }, [token, site.isPublished]);

  async function saveSection(key: string, value: object) {
    setSaving(key);
    try {
      const res = await fetch("/api/portal/website", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ token, contentKey: key, contentValue: value }),
      });
      const data = await res.json() as { ok: boolean };
      if (data.ok) {
        setContent(c => ({ ...c, [key]: value }));
        toast.success(`${SECTIONS.find(s => s.key === key)?.title ?? "Section"} saved.`);
      } else toast.error("Could not save. Please try again.");
    } finally { setSaving(null); }
  }

  async function updateAppearance(patch: Partial<CoupleWebsite>) {
    setSaving("appearance");
    try {
      const res = await fetch("/api/portal/website", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ token, theme: patch.theme, accentColor: patch.accentColor }),
      });
      const data = await res.json() as { ok: boolean };
      if (data.ok) { setSite(s => ({ ...s, ...patch })); toast.success("Appearance updated."); }
    } finally { setSaving(null); }
  }

  async function togglePublish() {
    setPublishing(true);
    const next = !site.isPublished;
    try {
      const res = await fetch("/api/portal/website", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ token, isPublished: next }),
      });
      const data = await res.json() as { ok: boolean };
      if (data.ok) {
        setSite(s => ({ ...s, isPublished: next }));
        toast.success(next ? "🎉 Your website is live!" : "Website set to draft.");
      }
    } finally { setPublishing(false); }
  }

  return (
    <div className="space-y-4">
      {/* Status header */}
      <div className="rounded-2xl border border-border bg-card p-4 space-y-3">
        {site.isPublished ? (
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="text-lg">🎉</span>
              <div>
                <p className="text-sm font-semibold text-heading">Your wedding website is live!</p>
                <p className="text-xs text-muted-foreground">Share the link with your guests.</p>
              </div>
            </div>
            {websiteUrl && (
              <div className="flex gap-2">
                <div className="flex-1 bg-muted/40 rounded-xl px-3 py-2 text-[11px] font-mono text-muted-foreground truncate">{websiteUrl}</div>
                <button type="button" onClick={() => { navigator.clipboard.writeText(websiteUrl); toast.success("Link copied!"); }}
                  className="shrink-0 px-3 py-1.5 rounded-xl border border-border text-xs hover:bg-muted transition-colors">Copy</button>
                <a href={websiteUrl} target="_blank" rel="noopener noreferrer"
                  className="shrink-0 px-3 py-1.5 rounded-xl border border-border text-xs hover:bg-muted transition-colors flex items-center gap-1">
                  <ExternalLink className="h-3 w-3" />
                </a>
              </div>
            )}
          </div>
        ) : (
          <div className="flex items-center gap-3">
            <span className="text-lg">✨</span>
            <div className="flex-1">
              <p className="text-sm font-semibold text-heading">
                {completedSections === 0 ? "Start building your website" : `${completedSections} of ${SECTIONS.length} sections added`}
              </p>
              <p className="text-xs text-muted-foreground">
                {completedSections === 0 ? "Add your details below and publish when you're ready." : "Looking great — publish when you're ready to share."}
              </p>
            </div>
          </div>
        )}
        <button type="button" onClick={togglePublish} disabled={publishing}
          className={`w-full rounded-xl py-2.5 text-sm font-semibold transition-colors disabled:opacity-60 ${
            site.isPublished
              ? "border border-border text-muted-foreground hover:bg-muted/40"
              : "text-white"
          }`}
          style={!site.isPublished ? { background: "#5D6F5D" } : {}}>
          {publishing ? <Loader2 className="h-4 w-4 animate-spin mx-auto" />
            : site.isPublished ? "Unpublish website" : "🚀 Publish website"}
        </button>
      </div>

      {/* Analytics — shown when published */}
      {site.isPublished && views !== null && (
        <div className="rounded-2xl border border-border bg-card p-4">
          <div className="flex items-center gap-4">
            <div className="text-center flex-1">
              <p className="text-2xl font-bold text-heading">{views.totalViews}</p>
              <p className="text-[10px] text-muted-foreground">Total visits</p>
            </div>
            <div className="text-center flex-1">
              <p className="text-2xl font-bold text-heading">{views.weekViews}</p>
              <p className="text-[10px] text-muted-foreground">This week</p>
            </div>
            <div className="text-center flex-1">
              <p className="text-2xl font-bold text-heading">{completedSections}</p>
              <p className="text-[10px] text-muted-foreground">Sections</p>
            </div>
          </div>
          {views.totalViews > 0 && (
            <p className="text-center text-xs mt-3" style={{ color: "#5D6F5D" }}>
              ✨ {views.totalViews === 1 ? "1 guest has visited your website." : `${views.totalViews} guests have visited your website.`}
            </p>
          )}
        </div>
      )}

      {/* Share & Preview */}
      {websiteUrl && (
        <div className="rounded-2xl border border-border bg-card p-4 space-y-3">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Share your website</p>
          <div className="grid grid-cols-2 gap-2">
            <button type="button" onClick={() => { navigator.clipboard.writeText(websiteUrl); toast.success("Link copied!"); }}
              className="flex items-center justify-center gap-1.5 rounded-xl border border-border py-2.5 text-xs font-medium hover:bg-muted/40 transition-colors">
              <Copy className="h-3.5 w-3.5" /> Copy link
            </button>
            <a href={`mailto:?subject=Our Wedding Website&body=Join us for our wedding! ${websiteUrl}`}
              className="flex items-center justify-center gap-1.5 rounded-xl border border-border py-2.5 text-xs font-medium hover:bg-muted/40 transition-colors">
              <Mail className="h-3.5 w-3.5" /> Share via email
            </a>
            <button type="button" onClick={() => { navigator.clipboard.writeText(`${websiteUrl}#rsvp`); toast.success("RSVP link copied!"); }}
              className="flex items-center justify-center gap-1.5 rounded-xl border border-border py-2.5 text-xs font-medium hover:bg-muted/40 transition-colors">
              💗 Copy RSVP link
            </button>
            <button type="button" onClick={() => setShowPreview(!showPreview)}
              className={`flex items-center justify-center gap-1.5 rounded-xl border py-2.5 text-xs font-medium transition-colors ${showPreview ? "bg-[#5D6F5D] text-white border-[#5D6F5D]" : "border-border hover:bg-muted/40"}`}>
              <Smartphone className="h-3.5 w-3.5" /> {showPreview ? "Hide" : "Preview"}
            </button>
            <button type="button" onClick={() => setShowQR(!showQR)}
              className={`flex items-center justify-center gap-1.5 rounded-xl border py-2.5 text-xs font-medium transition-colors ${showQR ? "bg-[#5D6F5D] text-white border-[#5D6F5D]" : "border-border hover:bg-muted/40"}`}>
              ▦ QR Code
            </button>
          </div>

          {/* QR Code */}
          {showQR && websiteUrl && (
            <div className="space-y-2 text-center">
              <img src={`/api/portal/website/qr?url=${encodeURIComponent(websiteUrl)}`}
                alt="Website QR code" className="h-40 w-40 mx-auto rounded-xl border border-border" />
              <p className="text-xs text-muted-foreground">Share this QR code on save-the-dates, printed invitations, and signage.</p>
              <a href={`/api/portal/website/qr?url=${encodeURIComponent(websiteUrl)}`} download="wedding-qr.svg"
                className="inline-block text-xs font-medium px-4 py-2 rounded-xl border border-border hover:bg-muted/40 transition-colors">
                Download QR Code
              </a>
            </div>
          )}

          {/* Send Invitations */}
          {guests.filter(g => g.email).length > 0 && (
            <div className="space-y-3">
              <button type="button" onClick={() => setShowInvite(!showInvite)}
                className={`w-full flex items-center justify-between px-4 py-3 rounded-xl border text-sm font-medium transition-colors ${showInvite ? "bg-[#5D6F5D] text-white border-[#5D6F5D]" : "border-border hover:bg-muted/40"}`}>
                <span>💌 Send Invitations</span>
                <span className="text-xs opacity-70">{guests.filter(g => g.email && !g.rsvpSentAt).length} guests not yet invited</span>
              </button>
              {showInvite && (
                <div className="rounded-2xl border border-border bg-card p-4 space-y-3">
                  <div className="flex items-center justify-between">
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Select guests to invite</p>
                    <button type="button" onClick={() => setSelectedGuests(
                      selectedGuests.length === guests.filter(g => g.email).length
                        ? [] : guests.filter(g => g.email).map(g => g.id)
                    )} className="text-xs text-muted-foreground hover:text-foreground">
                      {selectedGuests.length === guests.filter(g => g.email).length ? "Deselect all" : "Select all"}
                    </button>
                  </div>
                  <div className="space-y-1 max-h-48 overflow-y-auto">
                    {guests.filter(g => g.email).map(g => (
                      <label key={g.id} className="flex items-center gap-3 py-2 px-2 rounded-lg hover:bg-muted/30 cursor-pointer">
                        <input type="checkbox" checked={selectedGuests.includes(g.id)}
                          onChange={e => setSelectedGuests(prev => e.target.checked ? [...prev, g.id] : prev.filter(id => id !== g.id))}
                          className="rounded" />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-heading truncate">{[g.firstName, g.lastName].filter(Boolean).join(" ")}</p>
                          <p className="text-xs text-muted-foreground truncate">{g.email}</p>
                        </div>
                        {g.rsvpSentAt && <span className="text-[10px] text-muted-foreground">Sent</span>}
                        {g.rsvpStatus === "attending" && <span className="text-[10px] text-green-600">✓ Attending</span>}
                      </label>
                    ))}
                  </div>
                  <button type="button" disabled={selectedGuests.length === 0 || sendingInvites}
                    onClick={async () => {
                      setSendingInvites(true);
                      try {
                        const res = await fetch("/api/portal/invite", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, guestIds: selectedGuests }) });
                        const data = await res.json() as { ok: boolean; sent?: number; failed?: number };
                        if (data.ok) { toast.success(`${data.sent} invitation${data.sent !== 1 ? "s" : ""} sent!`); setShowInvite(false); setSelectedGuests([]); }
                        else toast.error("Some invitations failed. Please try again.");
                      } finally { setSendingInvites(false); }
                    }}
                    className="w-full rounded-xl py-2.5 text-sm font-semibold text-white disabled:opacity-50"
                    style={{ background: "#5D6F5D" }}>
                    {sendingInvites ? <Loader2 className="h-4 w-4 animate-spin mx-auto" /> : `Send ${selectedGuests.length > 0 ? selectedGuests.length + " " : ""}Invitation${selectedGuests.length !== 1 ? "s" : ""}`}
                  </button>
                </div>
              )}
            </div>
          )}

          {/* Live preview iframe */}
          {showPreview && (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <div className="flex rounded-lg border border-border overflow-hidden text-xs">
                  <button type="button" onClick={() => setPreviewMode("mobile")}
                    className={`px-2.5 py-1 transition-colors ${previewMode === "mobile" ? "bg-[#5D6F5D] text-white" : "text-muted-foreground"}`}>
                    📱
                  </button>
                  <button type="button" onClick={() => setPreviewMode("desktop")}
                    className={`px-2.5 py-1 transition-colors ${previewMode === "desktop" ? "bg-[#5D6F5D] text-white" : "text-muted-foreground"}`}>
                    🖥
                  </button>
                </div>
                <a href={websiteUrl} target="_blank" rel="noopener noreferrer"
                  className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1">
                  <ExternalLink className="h-3 w-3" /> Open full site
                </a>
              </div>
              <div className={`rounded-2xl overflow-hidden border border-border bg-muted/10 mx-auto transition-all ${previewMode === "mobile" ? "max-w-[320px]" : "w-full"}`}
                style={{ height: previewMode === "mobile" ? "560px" : "400px" }}>
                <iframe
                  src={websiteUrl}
                  className="w-full h-full border-0 rounded-2xl"
                  title="Website preview"
                  style={previewMode === "desktop" ? { transform: "scale(0.7)", transformOrigin: "top left", width: "143%", height: "143%" } : {}}
                />
              </div>
            </div>
          )}
        </div>
      )}

      {/* Section editors */}
      <div className="space-y-2">
        {SECTIONS.map(section => (
          <SectionAccordion key={section.key} section={section} content={content}
            onSaveSection={saveSection} saving={saving} token={token}
            scheduleSync={section.key === "schedule" ? scheduleSync : undefined}
            onToggleSync={section.key === "schedule" ? async (v) => {
              setScheduleSync(v);
              await fetch("/api/portal/website", {
                method: "POST", headers: { "content-type": "application/json" },
                body: JSON.stringify({ token, scheduleSync: v }),
              });
            } : undefined}
          />
        ))}
        <AppearanceSection site={site} onUpdate={updateAppearance} />
      </div>
    </div>
  );
}
