/**
 * Shared Relationship Operations — used by marketing (writes) and workspace (reads).
 *
 * Data path: RELATIONSHIPS_DATA_PATH or <repo>/shared/relationships/.data/
 * Format: JSONL files with a process-safe lock file.
 */

export type * from "./types";
export {
  normalizeEmail,
  normalizeVenueName,
  splitPersonName,
  mapPlanId,
  planDisplayName,
} from "./normalize";
export {
  getFounderProgramCapacity,
  computeFounderRemaining,
  resolveFounderSpotsRemaining,
} from "./founder-program";
export { getRelationshipsDataDir, STORE_FILES } from "./paths";
export { promoteStatus, stageLabelForStatus, toPipelineStatus, normalizeLifecycleStatus, isCustomerLifecycleStatus } from "./status";
export {
  type SalesStage,
  type CustomerSuccessStage,
  type CustomerSuccessFlag,
  type CustomerHealthBadge,
  type AdoptionCheckpoint,
  type RiskTone,
  type AutoArrivalBoard,
  type LastAutoArrival,
  SALES_STAGE_COLUMNS,
  CS_STAGE_COLUMNS,
  CS_FLAG_FILTERS,
  SALES_STAGE_LABELS,
  CS_STAGE_LABELS,
  CS_FLAG_LABELS,
  HEALTH_BADGE_LABELS,
  SALES_AUTO_ARRIVAL_STAGES,
  CS_AUTO_ARRIVAL_STAGES,
  isSalesStage,
  isCustomerSuccessStage,
  isCustomerSuccessFlag,
  resolveCustomerSuccessFlag,
  matchesCustomerSuccessFlag,
  isSalesAutoArrivalStage,
  isCsAutoArrivalStage,
  isInCustomerSuccessView,
  isInSalesView,
  relationshipHasOpenSupport,
  normalizeSalesStage,
  normalizeCustomerSuccessStage,
  deriveSalesStage,
  deriveCustomerSuccessStage,
  salesStageFromLifecycleStatus,
  promoteSalesStage,
  promoteCustomerSuccessStage,
  promoteToNeedsSupport,
  restoreFromNeedsSupport,
  markAutoArrival,
  clearAutoArrival,
  hasUnackedAutoArrival,
  countAutoArrivalsForStage,
  toCustomerHealthBadge,
  computeAdoptionCheckpoints,
  computeRiskSection,
  applySubscribeViewTransition,
} from "./sales-cs";
export {
  computeRelationshipHealth,
  applyHealthSnapshot,
  type RelationshipHealthSnapshot,
} from "./health";
export {
  enterOnboardingAfterPurchase,
  createManualSubscription,
  launchWhiteGloveWorkspace,
  whiteGloveLaunchReady,
  suspendRelationshipAccount,
  reactivateRelationshipAccount,
  recordPaymentFailed,
  markDunningReminderSent,
  tickPaymentDunning,
  refreshRelationshipHealth,
  recordSubscriptionLinkSent,
  whiteGloveTimelineLabel,
  DEFAULT_WHITE_GLOVE_TIMELINE_DAYS,
  ACTIVATION_TOKEN_TTL_MS,
  isActivationTokenExpired,
  lookupActivationToken,
  completeAccountActivation,
  type WhiteGloveTimelineSettings,
  type ActivationLookupResult,
} from "./lifecycle";
export {
  syncRenewalDate,
  initialRenewalDateIso,
  desiredRenewalStageForAnniversary,
  applyRenewalStageEvaluation,
  tickRenewalStages,
  tickRenewalStageForRelationship,
  addUtcYearsIso,
  utcDayMs,
  type RenewalStageTarget,
  type ApplyRenewalStageResult,
  type TickRenewalResult,
} from "./renewal-stages";
export {
  loadLiveStore,
  loadLiveStoreSync,
  hasLiveRelationships,
  hasLiveRelationshipsSync,
  saveLiveStore,
  withLiveStore,
  emptyLiveStore,
} from "./store";
export {
  findOrCreateRelationship,
  updateRelationshipFields,
  clearRelationshipAutoArrival,
  acknowledgeStageAutoArrivals,
  setRelationshipStatus,
  appendTimelineEvent,
  appendCommunication,
  upsertWalkthrough,
  upsertSubscription,
  appendNotification,
  markNotificationsRead,
  mutateRelationship,
  syncRelationshipFromProduct,
  resolveWelcomeBackVerification,
  resolveOpenFeedback,
  resolveSupportInboxItem,
  completeRelationshipTask,
  setWalkthroughStatus,
  personFromFields,
  type FindOrCreateResult,
  type SyncFromProductMatchBy,
  type SyncRelationshipFromProductResult,
  type WelcomeBackAction,
  type WelcomeBackResolveResult,
  type ResolveOpenFeedbackResult,
  type ResolveSupportInboxResult,
  type WalkthroughStatusUpdateResult,
} from "./service";
export {
  parseFromEmail,
  extractRelationshipIdFromAddresses,
  extractReplyMessageIds,
  normalizeMessageIdToken,
  matchRelationshipForInboundReply,
  recordInboundEmailReply,
  type InboundEmailPayload,
  type InboundMatchMethod,
  type InboundMatchResult,
  type RecordInboundEmailResult,
} from "./inbound-email";
export {
  ingestContactForm,
  ingestWalkthroughRequest,
  ingestWalkthroughCanceled,
  ingestManualRelationship,
  ingestCheckoutStarted,
  ingestSubscriptionPurchased,
  ingestSubscriptionLifecycle,
  ingestWelcomeBackRequest,
  ingestNewsletterSignup,
  ingestSupportRequest,
  ingestProductFeedback,
  ingestProductPartnerFeedback,
} from "./ingest";
export {
  WHITE_GLOVE_CHECKLIST_TITLES,
  WHITE_GLOVE_CHECKLIST_OWNER_ID,
  WHITE_GLOVE_CHECKLIST_MARKER,
  ensureWhiteGloveChecklist,
  ensureWhiteGloveChecklistInStore,
  ensureWhiteGloveChecklistsForLiveStore,
  isWhiteGloveChecklistTitle,
} from "./white-glove-checklist";
