import type {
  CommissionEventType,
  CommissionLedgerEntry,
  CommissionPlan,
  TeamMemberProfile,
} from "./types";

export const PLAN_IDS = {
  salesStandard: "plan_sales_standard",
  csRenewal: "plan_cs_renewal",
  implementation: "plan_implementation",
  leadership: "plan_leadership",
  none: "plan_none",
} as const;

export const SEED_COMMISSION_PLANS: CommissionPlan[] = [
  {
    id: PLAN_IDS.salesStandard,
    name: "Sales Standard",
    description: "Walkthrough booking bonus plus subscription and White Glove rates.",
    active: true,
    rates: {
      walkthrough_booked: { mode: "flat", cents: 5000 },
      subscription_sold: { mode: "percent", bps: 1000 },
      white_glove_sold: { mode: "flat", cents: 20000 },
      renewal: { mode: "percent", bps: 500 },
      referral: { mode: "flat", cents: 15000 },
      expansion: { mode: "percent", bps: 800 },
    },
  },
  {
    id: PLAN_IDS.csRenewal,
    name: "CS Retention",
    description: "Renewal, referral, and expansion bonuses for Customer Success.",
    active: true,
    rates: {
      renewal: { mode: "flat", cents: 7500 },
      referral: { mode: "flat", cents: 10000 },
      expansion: { mode: "flat", cents: 10000 },
      white_glove_sold: { mode: "flat", cents: 5000 },
    },
  },
  {
    id: PLAN_IDS.implementation,
    name: "Implementation Assist",
    description: "Small bonus when White Glove deals close into onboarding.",
    active: true,
    rates: {
      white_glove_sold: { mode: "flat", cents: 7500 },
      subscription_sold: { mode: "flat", cents: 2500 },
    },
  },
  {
    id: PLAN_IDS.leadership,
    name: "Leadership Override",
    description: "Owner / admin override — typically $0; used for attribution only.",
    active: true,
    rates: {},
  },
  {
    id: PLAN_IDS.none,
    name: "No Commission",
    description: "Support, marketing, and viewer roles without variable pay.",
    active: true,
    rates: {},
  },
];

export const SEED_TEAM: TeamMemberProfile[] = [
  {
    id: "tm_jen",
    name: "Jennifer Marshall",
    email: "jennifer@hellotocheers.com",
    initials: "JM",
    role: "owner",
    title: "Founder & Owner",
    department: "leadership",
    commissionPlanId: PLAN_IDS.leadership,
    goals: [
      {
        id: "g_jen_mrr",
        label: "MRR",
        target: 200000,
        current: 129500,
        unit: "currency_cents",
        period: "quarter",
      },
      {
        id: "g_jen_founders",
        label: "Founding members",
        target: 100,
        current: 42,
        unit: "count",
        period: "year",
      },
    ],
    availability: "available",
    territory: null,
    active: true,
    joinedAt: "2024-01-15T12:00:00.000Z",
  },
  {
    id: "tm_maya",
    name: "Maya Chen",
    email: "maya@hellotocheers.com",
    initials: "MC",
    role: "customer_success",
    title: "Success Lead",
    department: "customer_success",
    commissionPlanId: PLAN_IDS.csRenewal,
    goals: [
      {
        id: "g_maya_renewals",
        label: "Renewals saved",
        target: 8,
        current: 3,
        unit: "count",
        period: "quarter",
      },
      {
        id: "g_maya_nps",
        label: "Health excellent+",
        target: 80,
        current: 72,
        unit: "percent",
        period: "quarter",
      },
    ],
    availability: "available",
    territory: "Southeast",
    active: true,
    joinedAt: "2025-03-01T12:00:00.000Z",
  },
  {
    id: "tm_eli",
    name: "Eli Torres",
    email: "eli@hellotocheers.com",
    initials: "ET",
    role: "implementation",
    title: "Onboarding Specialist",
    department: "implementation",
    commissionPlanId: PLAN_IDS.implementation,
    goals: [
      {
        id: "g_eli_go_lives",
        label: "Go-lives",
        target: 6,
        current: 2,
        unit: "count",
        period: "month",
      },
    ],
    availability: "busy",
    territory: null,
    active: true,
    joinedAt: "2025-06-10T12:00:00.000Z",
  },
  {
    id: "tm_sara",
    name: "Sara Whitfield",
    email: "sara@hellotocheers.com",
    initials: "SW",
    role: "sales",
    title: "Walkthroughs & Sales",
    department: "sales",
    commissionPlanId: PLAN_IDS.salesStandard,
    goals: [
      {
        id: "g_sara_wt",
        label: "Walkthroughs booked",
        target: 20,
        current: 11,
        unit: "count",
        period: "month",
      },
      {
        id: "g_sara_subs",
        label: "Subscriptions closed",
        target: 8,
        current: 4,
        unit: "count",
        period: "month",
      },
    ],
    availability: "available",
    territory: "National remote",
    active: true,
    joinedAt: "2025-02-18T12:00:00.000Z",
  },
  {
    id: "tm_noah",
    name: "Noah Patel",
    email: "noah@hellotocheers.com",
    initials: "NP",
    role: "support",
    title: "Support Specialist",
    department: "support",
    commissionPlanId: PLAN_IDS.none,
    goals: [
      {
        id: "g_noah_sla",
        label: "First response < 4h",
        target: 95,
        current: 91,
        unit: "percent",
        period: "month",
      },
    ],
    availability: "available",
    territory: null,
    active: true,
    joinedAt: "2025-09-01T12:00:00.000Z",
  },
  {
    id: "tm_ava",
    name: "Ava Brooks",
    email: "ava@hellotocheers.com",
    initials: "AB",
    role: "finance",
    title: "Finance Partner",
    department: "finance",
    commissionPlanId: PLAN_IDS.none,
    goals: [
      {
        id: "g_ava_collections",
        label: "Collections on time",
        target: 98,
        current: 94,
        unit: "percent",
        period: "quarter",
      },
    ],
    availability: "part_time",
    territory: null,
    active: true,
    joinedAt: "2025-11-12T12:00:00.000Z",
  },
  {
    id: "tm_leo",
    name: "Leo Kim",
    email: "leo@hellotocheers.com",
    initials: "LK",
    role: "marketing",
    title: "Growth Marketing",
    department: "marketing",
    commissionPlanId: PLAN_IDS.none,
    goals: [
      {
        id: "g_leo_inquiries",
        label: "Qualified inquiries",
        target: 40,
        current: 27,
        unit: "count",
        period: "month",
      },
    ],
    availability: "available",
    territory: null,
    active: true,
    joinedAt: "2026-01-08T12:00:00.000Z",
  },
  {
    id: "tm_admin",
    name: "Casey Rivera",
    email: "casey@hellotocheers.com",
    initials: "CR",
    role: "administrator",
    title: "Operations Admin",
    department: "leadership",
    commissionPlanId: PLAN_IDS.leadership,
    goals: [],
    availability: "available",
    territory: null,
    active: true,
    joinedAt: "2025-08-20T12:00:00.000Z",
  },
];

/** Sample ledger entries for demo — Jul 2026 period. */
export const SEED_COMMISSION_LEDGER: CommissionLedgerEntry[] = [
  {
    id: "cl_1",
    teamMemberId: "tm_sara",
    relationshipId: "rel_harbor",
    eventType: "walkthrough_booked",
    sourceEventId: "seed_wt_harbor",
    basisCents: 0,
    commissionCents: 5000,
    planId: PLAN_IDS.salesStandard,
    occurredAt: "2026-07-17T15:00:00.000Z",
    periodKey: "2026-07",
    status: "approved",
    note: "Harbor House walkthrough completed → booked attribution",
  },
  {
    id: "cl_2",
    teamMemberId: "tm_sara",
    relationshipId: "rel_meadow",
    eventType: "subscription_sold",
    sourceEventId: "seed_sub_meadow",
    basisCents: 14900,
    commissionCents: 1490,
    planId: PLAN_IDS.salesStandard,
    occurredAt: "2026-07-21T11:00:00.000Z",
    periodKey: "2026-07",
    status: "pending",
    note: "Gather · first month MRR × 10%",
  },
  {
    id: "cl_3",
    teamMemberId: "tm_sara",
    relationshipId: "rel_pinecrest",
    eventType: "white_glove_sold",
    sourceEventId: "seed_wg_pinecrest",
    basisCents: 0,
    commissionCents: 20000,
    planId: PLAN_IDS.salesStandard,
    occurredAt: "2026-07-12T18:00:00.000Z",
    periodKey: "2026-07",
    status: "approved",
  },
  {
    id: "cl_4",
    teamMemberId: "tm_eli",
    relationshipId: "rel_pinecrest",
    eventType: "white_glove_sold",
    sourceEventId: "seed_wg_pinecrest_impl",
    basisCents: 0,
    commissionCents: 7500,
    planId: PLAN_IDS.implementation,
    occurredAt: "2026-07-12T18:05:00.000Z",
    periodKey: "2026-07",
    status: "pending",
    note: "Implementation assist on White Glove",
  },
  {
    id: "cl_5",
    teamMemberId: "tm_maya",
    relationshipId: "rel_oakridge",
    eventType: "renewal",
    sourceEventId: "seed_ren_oakridge",
    basisCents: 39900,
    commissionCents: 7500,
    planId: PLAN_IDS.csRenewal,
    occurredAt: "2026-07-05T14:00:00.000Z",
    periodKey: "2026-07",
    status: "paid",
    note: "Flourish renewal",
  },
  {
    id: "cl_6",
    teamMemberId: "tm_maya",
    relationshipId: "rel_solstice",
    eventType: "referral",
    sourceEventId: "seed_ref_solstice",
    basisCents: 0,
    commissionCents: 10000,
    planId: PLAN_IDS.csRenewal,
    occurredAt: "2026-07-10T16:00:00.000Z",
    periodKey: "2026-07",
    status: "approved",
  },
];

export const COMMISSION_EVENT_LABELS: Record<CommissionEventType, string> = {
  walkthrough_booked: "Walkthrough booked",
  subscription_sold: "Subscription sold",
  white_glove_sold: "White Glove sold",
  renewal: "Renewal",
  referral: "Referral",
  expansion: "Expansion",
};

export const DEFAULT_ACTOR_ID = "tm_jen";
